using DbManager.Parser;
using System;


namespace DbManager
{
    public class ColumnDefinition
    {
        public enum DataType { String, Int, Double}

        public DataType Type;
        public string Name { get; private set; }


        public ColumnDefinition(DataType type, string name)
        {
            //TODO DEADLINE 1.A: Initialize member variables
           this.Type = type;
            this.Name = name;
        }

        private const string Delimiter = "->";
        private const string DelimiterEncoded = "[ARROW]";

        private static string Encode(string value)
        {
            //TODO DEADLINE 1.C: Encode the delimiter in the value
            if(value == null)
            {
                return null;
            }
            value = value.Replace(Delimiter, DelimiterEncoded);
            return value;
            
        }

        private static string Decode(string value)
        {
            //TODO DEADLINE 1.C: Decode the delimiter in the value
            if(value == null)
            {
                return null;
            }
           value = value.Replace(DelimiterEncoded,Delimiter);
            return value;
        }

        public string AsText()
        {
            //TODO DEADLINE 1.C: Return the column as a string with the name and the type separated by the delimiter
           string nombre = Encode(this.Name);
            return nombre+Delimiter+this.Type.ToString();
        }

        public static ColumnDefinition Parse(string value)
        {
            //TODO DEADLINE 1.C: Parse the column's name and type from a string generated by AsText()
            int posicion = value.IndexOf(Delimiter);
            String nombre = value.Substring(0,posicion);
            String tipo = value.Substring(posicion + Delimiter.Length);
            String nombreDecodificado = Decode(nombre);
            
            return null;
            
        }
    }
}
